# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84c9e44d01e642eb84ec4fc30e9b31d2f70bde61103a924303d397dac29a218be4b83af1cf0df14fcd942ffd2946c098b0c73eec5f8840b130e5a72ed4409657

test:
  secret_key_base: 58d094191cca0d2ce6abf16f7a86f534b91506e5cab3c8e12b9e604fa66123fe9dcc8a2a9273756c4dc9c70bf6fd434acd4be3ce61ab4a569632dac9b5486df9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
